### ISSUE TITLE
[BUG] Clicking on chart slices/links in the 'Schedule' page returns a 404

### ISSUE THREAD

**Issue by sakhawy** [djangocon/2024.djangocon.eu#46] opened 2024-04-05 12:20 UTC
Visiting `talks/schedule/` and clicking on chart links/slices returns a 404 not found:

```

Page not found (404)
Request Method: 	GET
Request URL: 	http://0.0.0.0:8000/orga/event/djangocon-europe-2024/speakers/?&question=91&answer__options=12

Using the URLconf defined in config.urls, Django tried these URL patterns, in this order:

    __debug__/
    <slug:menu>/
    <slug:menu>/<slug:submenu>/
    ^media/(?P<path>.*)$
    400/
    403/
    404/
    500/

The current path, orga/event/djangocon-europe-2024/speakers/, didn’t match any of these.

You’re seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard 404 page.
```

(Also, `DEBUG` is `True` enabling me to see this)

**Comment by Darkbeast-glitch** [comment] 2024-04-07 11:32
Thank you i will check that,
![image](https://github.com/djangocon/2024.djangocon.eu/assets/66005635/9852f28f-ffd9-4437-8d63-2b5fcd045e89)
Debug is False by default , I am sure David  will check that out

**Comment by Darkbeast-glitch** [comment] 2024-04-08 01:10
Hey @sakhawy the issue is solved, i will close the issue now

**Closed as completed by Darkbeast-glitch** 2024-04-08 01:10 UTC
